export const PinterestPreset = {
  primitive: {
    borderRadius: {
      none: '0',
      xs: '2px',
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '24px',
      full: '9999px',
    },
    red: {
      50: '#FFF0F1',
      100: '#FFD6DB',
      200: '#FFACB8',
      300: '#FF8294',
      400: '#FF4761',
      500: '#E60023',
      600: '#CC001F',
      700: '#AD081B',
      800: '#8B0517',
      900: '#6B0412',
      950: '#3D010A',
    },
    gray: {
      0: '#ffffff',
      50: '#F8F8F8',
      100: '#F0F0F0',
      200: '#E0E0E0',
      300: '#C8C8C8',
      400: '#ADADAD',
      500: '#767676',
      600: '#555555',
      700: '#404040',
      800: '#2D2D2D',
      900: '#1A1A1A',
      950: '#111111',
    },
    white: '#ffffff',
    black: '#000000',
  },
  semantic: {
    transitionDuration: '0.15s',
    iconSize: '1.25rem',
    anchorGutter: '2px',
    primary: {
      50: '{red.50}',
      100: '{red.100}',
      200: '{red.200}',
      300: '{red.300}',
      400: '{red.400}',
      500: '{red.500}',
      600: '{red.600}',
      700: '{red.700}',
      800: '{red.800}',
      900: '{red.900}',
      950: '{red.950}',
    },
    formField: {
      paddingX: '0.75rem',
      paddingY: '0.5rem',
      sm: { fontSize: '0.875rem', paddingX: '0.625rem', paddingY: '0.375rem' },
      lg: { fontSize: '1.125rem', paddingX: '0.875rem', paddingY: '0.625rem' },
      borderRadius: '{border.radius.md}',
      focusRing: { width: '2px', style: 'solid', color: '{primary.500}', offset: '0px' },
      transitionDuration: '{transition.duration}',
    },
    list: {
      padding: '0.25rem 0',
      gap: '2px',
      header: { padding: '0.5rem 0.75rem 0.25rem' },
      option: { padding: '0.5rem 0.75rem', borderRadius: '{border.radius.sm}' },
      optionGroup: { padding: '0.5rem 0.75rem', fontWeight: '600' },
    },
    content: {
      borderRadius: '{border.radius.md}',
    },
    mask: {
      transitionDuration: '0.15s',
    },
    navigation: {
      list: { padding: '0.25rem 0', gap: '2px' },
      item: { padding: '0.5rem 0.75rem', borderRadius: '{border.radius.sm}', gap: '0.5rem' },
      submenuLabel: { padding: '0.5rem 0.75rem', fontWeight: '600' },
      submenuIcon: { size: '0.875rem' },
    },
    overlay: {
      select: { borderRadius: '{border.radius.md}', shadow: '0 4px 16px rgba(0,0,0,0.12)' },
      popover: { borderRadius: '{border.radius.xl}', padding: '0.75rem', shadow: '0 4px 16px rgba(0,0,0,0.12)' },
      modal: { borderRadius: '{border.radius.xl}', padding: '1.5rem', shadow: '0 16px 48px rgba(0,0,0,0.16)' },
      navigation: { shadow: '0 4px 16px rgba(0,0,0,0.12)' },
    },
    colorScheme: {
      light: {
        surface: {
          0: '#ffffff',
          50: '{gray.50}',
          100: '{gray.100}',
          200: '{gray.200}',
          300: '{gray.300}',
          400: '{gray.400}',
          500: '{gray.500}',
          600: '{gray.600}',
          700: '{gray.700}',
          800: '{gray.800}',
          900: '{gray.900}',
          950: '{gray.950}',
        },
        primary: {
          color: '{primary.500}',
          contrastColor: '#ffffff',
          hoverColor: '{primary.600}',
          activeColor: '{primary.700}',
        },
        highlight: {
          background: '{primary.50}',
          focusBackground: '{primary.100}',
          color: '{primary.700}',
          focusColor: '{primary.800}',
        },
        focusRing: {
          shadow: '0 0 0 2px {primary.200}',
        },
        mask: {
          background: 'rgba(0,0,0,0.5)',
          color: '{surface.200}',
        },
        overlay: {
          select: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{surface.950}',
          },
          popover: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{surface.950}',
          },
          modal: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{surface.950}',
          },
        },
        list: {
          option: {
            focusBackground: '{surface.100}',
            selectedBackground: '{highlight.background}',
            selectedFocusBackground: '{highlight.focusBackground}',
            color: '{surface.950}',
            focusColor: '{surface.950}',
            selectedColor: '{highlight.color}',
            selectedFocusColor: '{highlight.focusColor}',
            icon: { color: '{surface.400}', focusColor: '{surface.600}' },
          },
          optionGroup: { background: 'transparent', color: '{surface.600}' },
        },
        content: {
          background: '{surface.0}',
          hoverBackground: '{surface.100}',
          borderColor: '{surface.200}',
          color: '{surface.950}',
          hoverColor: '{surface.950}',
        },
        text: {
          color: '{surface.950}',
          hoverColor: '{surface.950}',
          mutedColor: '{surface.500}',
          hoverMutedColor: '{surface.600}',
        },
        formField: {
          background: '{surface.0}',
          disabledBackground: '{surface.100}',
          filledBackground: '{surface.50}',
          filledHoverBackground: '{surface.100}',
          filledFocusBackground: '{surface.50}',
          borderColor: '{surface.300}',
          hoverBorderColor: '{surface.400}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.500}',
          color: '{surface.950}',
          disabledColor: '{surface.400}',
          placeholderColor: '{surface.400}',
          invalidPlaceholderColor: '{red.400}',
          floatLabelColor: '{surface.500}',
          floatLabelFocusColor: '{primary.color}',
          floatLabelActiveColor: '{surface.500}',
          floatLabelInvalidColor: '{red.500}',
          iconColor: '{surface.500}',
          shadow: 'none',
        },
        navigation: {
          item: {
            focusBackground: '{surface.100}',
            activeBackground: '{surface.100}',
            color: '{surface.700}',
            focusColor: '{surface.900}',
            activeColor: '{surface.900}',
            icon: {
              color: '{surface.500}',
              focusColor: '{surface.700}',
              activeColor: '{surface.700}',
            },
          },
          submenuLabel: { background: 'transparent', color: '{surface.500}' },
          submenuIcon: { color: '{surface.500}', focusColor: '{surface.700}', activeColor: '{surface.700}' },
        },
      },
      dark: {
        surface: {
          0: '#ffffff',
          50: '{gray.800}',
          100: '{gray.700}',
          200: '{gray.600}',
          300: '{gray.500}',
          400: '{gray.400}',
          500: '{gray.300}',
          600: '{gray.200}',
          700: '{gray.100}',
          800: '{gray.50}',
          900: '{gray.50}',
          950: '{gray.0}',
        },
        primary: {
          color: '{primary.500}',
          contrastColor: '#ffffff',
          hoverColor: '{primary.400}',
          activeColor: '{primary.300}',
        },
        highlight: {
          background: 'color-mix(in srgb,{primary.400},transparent 84%)',
          focusBackground: 'color-mix(in srgb,{primary.400},transparent 76%)',
          color: 'rgba(255,255,255,.87)',
          focusColor: 'rgba(255,255,255,.87)',
        },
        focusRing: {
          shadow: '0 0 0 2px {primary.700}',
        },
        mask: {
          background: 'rgba(0,0,0,0.6)',
          color: '{surface.200}',
        },
        overlay: {
          select: {
            background: '{gray.800}',
            borderColor: '{gray.700}',
            color: '{gray.0}',
          },
          popover: {
            background: '{gray.800}',
            borderColor: '{gray.700}',
            color: '{gray.0}',
          },
          modal: {
            background: '{gray.900}',
            borderColor: '{gray.700}',
            color: '{gray.0}',
          },
        },
        list: {
          option: {
            focusBackground: '{gray.700}',
            selectedBackground: '{highlight.background}',
            selectedFocusBackground: '{highlight.focusBackground}',
            color: 'rgba(255,255,255,.87)',
            focusColor: 'rgba(255,255,255,.87)',
            selectedColor: '{highlight.color}',
            selectedFocusColor: '{highlight.focusColor}',
            icon: { color: '{gray.400}', focusColor: '{gray.200}' },
          },
          optionGroup: { background: 'transparent', color: '{gray.400}' },
        },
        content: {
          background: '{gray.900}',
          hoverBackground: '{gray.800}',
          borderColor: '{gray.700}',
          color: 'rgba(255,255,255,.87)',
          hoverColor: 'rgba(255,255,255,.87)',
        },
        text: {
          color: 'rgba(255,255,255,.87)',
          hoverColor: 'rgba(255,255,255,.87)',
          mutedColor: '{gray.400}',
          hoverMutedColor: '{gray.300}',
        },
        formField: {
          background: '{gray.800}',
          disabledBackground: '{gray.700}',
          filledBackground: '{gray.700}',
          filledHoverBackground: '{gray.600}',
          filledFocusBackground: '{gray.700}',
          borderColor: '{gray.600}',
          hoverBorderColor: '{gray.500}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.400}',
          color: 'rgba(255,255,255,.87)',
          disabledColor: '{gray.400}',
          placeholderColor: '{gray.500}',
          invalidPlaceholderColor: '{red.300}',
          floatLabelColor: '{gray.400}',
          floatLabelFocusColor: '{primary.color}',
          floatLabelActiveColor: '{gray.400}',
          floatLabelInvalidColor: '{red.400}',
          iconColor: '{gray.400}',
          shadow: 'none',
        },
        navigation: {
          item: {
            focusBackground: '{gray.700}',
            activeBackground: '{gray.700}',
            color: 'rgba(255,255,255,.7)',
            focusColor: 'rgba(255,255,255,.87)',
            activeColor: 'rgba(255,255,255,.87)',
            icon: {
              color: '{gray.400}',
              focusColor: '{gray.200}',
              activeColor: '{gray.200}',
            },
          },
          submenuLabel: { background: 'transparent', color: '{gray.400}' },
          submenuIcon: { color: '{gray.400}', focusColor: '{gray.200}', activeColor: '{gray.200}' },
        },
      },
    },
  },
  components: {
    button: {
      root: {
        borderRadius: '{border.radius.full}',
        gap: '0.5rem',
        paddingX: '1rem',
        paddingY: '0.625rem',
        iconOnlyWidth: '2.5rem',
        sm: { fontSize: '0.875rem', paddingX: '0.75rem', paddingY: '0.5rem' },
        lg: { fontSize: '1.125rem', paddingX: '1.25rem', paddingY: '0.75rem' },
        label: { fontWeight: '600' },
        focusRing: { offset: '0px', shadow: '0 0 0 3px {primary.200}' },
        transitionDuration: '{transition.duration}',
      },
      colorScheme: {
        light: {
          root: {
            primary: {
              background: '{primary.500}',
              hoverBackground: '{primary.600}',
              activeBackground: '{primary.700}',
              borderColor: '{primary.500}',
              hoverBorderColor: '{primary.600}',
              activeBorderColor: '{primary.700}',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
              focusRing: { color: '{primary.500}', shadow: '0 0 0 3px {primary.200}' },
            },
            secondary: {
              background: '{surface.100}',
              hoverBackground: '{surface.200}',
              activeBackground: '{surface.300}',
              borderColor: '{surface.100}',
              hoverBorderColor: '{surface.200}',
              activeBorderColor: '{surface.300}',
              color: '{surface.900}',
              hoverColor: '{surface.900}',
              activeColor: '{surface.900}',
              focusRing: { color: '{surface.500}', shadow: '0 0 0 3px {surface.200}' },
            },
            contrast: {
              background: '{surface.950}',
              hoverBackground: '{surface.800}',
              activeBackground: '{surface.700}',
              borderColor: '{surface.950}',
              color: '{surface.0}',
              hoverColor: '{surface.0}',
              activeColor: '{surface.0}',
              focusRing: { color: '{surface.950}', shadow: '0 0 0 3px {surface.300}' },
            },
          },
          outlined: {
            primary: {
              hoverBackground: '{primary.50}',
              activeBackground: '{primary.100}',
              borderColor: '{primary.500}',
              color: '{primary.500}',
            },
            secondary: {
              hoverBackground: '{surface.100}',
              activeBackground: '{surface.200}',
              borderColor: '{surface.300}',
              color: '{surface.900}',
            },
          },
          text: {
            primary: {
              hoverBackground: '{primary.50}',
              activeBackground: '{primary.100}',
              color: '{primary.500}',
            },
            secondary: {
              hoverBackground: '{surface.100}',
              activeBackground: '{surface.200}',
              color: '{surface.600}',
            },
          },
          link: {
            color: '{primary.500}',
            hoverColor: '{primary.700}',
            activeColor: '{primary.700}',
          },
        },
        dark: {
          root: {
            primary: {
              background: '{primary.500}',
              hoverBackground: '{primary.400}',
              activeBackground: '{primary.300}',
              borderColor: '{primary.500}',
              hoverBorderColor: '{primary.400}',
              activeBorderColor: '{primary.300}',
              color: '#ffffff',
              hoverColor: '#ffffff',
              activeColor: '#ffffff',
              focusRing: { color: '{primary.400}', shadow: '0 0 0 3px {primary.700}' },
            },
            secondary: {
              background: '{gray.700}',
              hoverBackground: '{gray.600}',
              activeBackground: '{gray.500}',
              borderColor: '{gray.700}',
              color: 'rgba(255,255,255,.87)',
              hoverColor: 'rgba(255,255,255,.87)',
              activeColor: 'rgba(255,255,255,.87)',
              focusRing: { color: '{gray.300}', shadow: '0 0 0 3px {gray.600}' },
            },
          },
          text: {
            primary: { hoverBackground: '{primary.900}', activeBackground: '{primary.800}', color: '{primary.400}' },
            secondary: { hoverBackground: '{gray.700}', activeBackground: '{gray.600}', color: '{gray.400}' },
          },
        },
      },
    },
    inputtext: {
      root: {
        borderRadius: '{border.radius.full}',
        paddingX: '1rem',
        paddingY: '0.75rem',
        focusRing: { width: '0', offset: '0' },
      },
    },
    tooltip: {
      root: {
        maxWidth: '12rem',
        gutter: '6px',
        shadow: '0 4px 16px rgba(0,0,0,0.16)',
        padding: '0.4rem 0.75rem',
        borderRadius: '{border.radius.full}',
      },
      colorScheme: {
        light: {
          root: { background: '{gray.950}', color: '#ffffff', borderColor: 'transparent' },
          arrow: { background: '{gray.950}', borderColor: 'transparent' },
        },
        dark: {
          root: { background: '{gray.200}', color: '{gray.950}', borderColor: 'transparent' },
          arrow: { background: '{gray.200}', borderColor: 'transparent' },
        },
      },
    },
    dialog: {
      root: { borderRadius: '{border.radius.xl}', gap: '1.5rem' },
      header: { padding: '1.5rem 1.5rem 0', gap: '0.75rem' },
      content: { padding: '0 1.5rem' },
      footer: { padding: '0 1.5rem 1.5rem', gap: '0.5rem' },
    },
    avatar: {
      root: { width: '2.5rem', height: '2.5rem', fontSize: '1.125rem', borderRadius: '{border.radius.full}' },
      colorScheme: {
        light: { root: { background: '{surface.200}', color: '{surface.700}' } },
        dark: { root: { background: '{gray.700}', color: 'rgba(255,255,255,.87)' } },
      },
    },
    badge: {
      root: { borderRadius: '{border.radius.full}', padding: '0 0.375rem', fontSize: '0.75rem', fontWeight: '700', minWidth: '1.25rem', height: '1.25rem' },
      colorScheme: {
        light: {
          root: {
            primary: { background: '{primary.500}', color: '#ffffff' },
            secondary: { background: '{surface.200}', color: '{surface.700}' },
            danger: { background: '{red.500}', color: '#ffffff' },
          },
        },
        dark: {
          root: {
            primary: { background: '{primary.500}', color: '#ffffff' },
          },
        },
      },
    },
    skeleton: {
      root: { borderRadius: '{border.radius.md}' },
      colorScheme: {
        light: { root: { background: '{surface.200}', animationBackground: 'rgba(255,255,255,0.4)' } },
        dark: { root: { background: '{gray.700}', animationBackground: 'rgba(255,255,255,0.06)' } },
      },
    },
    tabs: {
      root: { transitionDuration: '0.15s' },
      tablist: { borderWidth: '0 0 2px 0', background: 'transparent', borderColor: '{surface.200}' },
      tab: { borderWidth: '0 0 2px 0', borderColor: 'transparent', activeBorderColor: '{primary.color}', color: '{text.muted.color}', hoverColor: '{text.color}', activeColor: '{primary.color}', fontWeight: '600', margin: '0 0 -2px 0', padding: '0.75rem 1rem', gap: '0.5rem', focusRing: { offset: '0', shadow: 'none' } },
      tabpanel: { background: 'transparent', color: '{text.color}', padding: '1rem 0', focusRing: { offset: '0', shadow: 'none' } },
      colorScheme: {
        light: { tablist: { borderColor: '{surface.200}' }, tab: { activeBorderColor: '{primary.500}', activeColor: '{primary.500}', color: '{surface.500}', hoverColor: '{surface.950}' } },
        dark: { tablist: { borderColor: '{gray.700}' }, tab: { activeBorderColor: '{primary.400}', activeColor: '{primary.400}', color: '{gray.400}', hoverColor: 'rgba(255,255,255,.87)' } },
      },
    },
  },
};
